language: python
python:
- '2.7'
sudo: required
services:
- docker
install:
- pip install dxpy
env:
  global:
    #DX_LOGIN_TOKEN
    #QUAY_LOGIN
    #QUAY_PASSWORD
  - secure: fUvNeNzIJ6sBoy85PkJ8y3NzPY6CFjEW1l7hAHOnWHfYC+1oCTLp1mBDTGWsxTK02rMntPziqE6uXYxneoDin2ieUqBu+CO3ztB4vLkGHJUoFx7cYlE7VkzgJamwrvvv9R1ircmehfhnztPNeDBlpKKR0yadSPDBqEJw9qTX2k+c8POk65lrLHpehc4FivsTc4KzihEJlFbWD9uGOusXcVhcUOn5KUVoLP4e7A1Dn38HX0mVdGD4B1FH7GpdUb1nroNz1Ia8fY2l43MN94FaQoc2p5AfWKQIoIueQzcNdC06G/OrqOWM1vkUSUv3Lg277v6V22ayHgnojYIVCDdd6ybjWrIsBoWIhZ3YifL8b8ooInCq9D3grsYZrixp5z6Xcm8An3Hu6nem6lPqb4pt33/MWMXlPGcfWHtlh2J66pawVg6qXJciLWKvPp2w20Eb+mQPpcXYVbeJJFVOSxWwPfSOLLSVwfYtGx96b50ZSOQ7XXTjKjecVmc0yulKBlDCWnenf84MWJHlKkf47EInm7Eb/2VjcqMy7WaFf0HcnV3l0ALCEBfMn0cgpC0x+ubpKvpLtpJf7OIFDVFMwtG/Pb3bx5uOLveT9DbtmE1qLIIuCTq06awBtjbe5hL2ru6iwyaY17Uphsqn8/hTUmMQf2hzC+hrWClnTqwv1ZHCAvA=
  - secure: IDBZ/1Mi0xz6Udj9RT44z/JejQVU0hOQN4sYHbFvkpPdBo7UmH9U7Rs3neZ9GbnxWfIvmuvYUdptBakhyANCJmHbTSbhoEMHZU59pLwjbee0v/OYB+RFDMm9buGuVNzBC9HXVW0qUm+kN8QnZ7OCcA+l/m4K99GJqbs+8fhloW5qErkuOmI9XDMJHZz4KUfw/0glnMvAZWIW6gn3PmBsUIrtQcT4rbD6+UI3sIkPUeNPn7O2/g0yDf4+e22rl2NjmkxcFg+jURtsaYikUNmR5f8F4C5l3Y7VGHgeLlQYZbMbIFDTcI8QdXU4SR2dqBWPYdM9j1bAkCzmHsO/unKY/wZ4xW7sFHGEIfUJgI0O7nzmKQPe7mscfucw0ljR2g2JfpkIVG1i03SrVRL2Tidd2HjnETsEfFL2bMJ8qDFA/VAw9eMve8tTGAPEOT+Nzr+olgM+iJq/VLb1jdlWhkcBRWfMAYH+Q8e+/QTa5YKztUQPI6tnLx9T1OHpkawd7bZTKHEocASdNnGiUxr3WwG7vN82dpQ1Pgxh+i0cnSm+kIqr5l9SeLLin6ZmQRfjZKp6xLu8Z0yuF+X2q0drlO7ZcixQxDYKwh54g/nS0fwpn5KF9KiX7oTY7bcweY9l5qVBfJW53TufyeWRZ6NW1dguVITWQUQ0cYwptiXgxIBNQJA=
  - secure: kG8afnga6Z9Npy7qOfj2lfTJVu5wwA72s1UkQ4K4YW7HNGmCxb3FlosYbvDqgTvgSyla8pvK9T0RXvJWtiRi8TuRX05qmIwURfj77+pXPk1qxt5IM0Xeg5R6DeGK2reBHKcKO+vkLDpMpPn5jw02jSK6CFsCmU5GtUSWmctnCKwlClUIh2BCOP4gORW0Q/h2V8B9shltAYJH5fNXDCPk6SP/qmhjjGMkIYoRXRQS8Y8GN8vKkZz8vqYnZVQmx2kny+lf0/nOBly8ACvQOcWiyrafNyHPsK14NuRQb0uWVPB3+uiYfVqjUt/qEazcSAwAf8N9XqLd/U8R7UmpHfR20/XuQN4nNkZF3czH19cgZwp7hrEy2v7o4+fLTE6onJmN5gdsumG3yGxIqLSpTANI1AOhqa1uZOKKWDy1dNQQXXIxSr8juf5pkPMhRib+SeSvR86dPcGBHbB8GKafqLNX4MDNh/X4KKVG8uiw+4DgsSqKFhSllm8m15fgXxe3Dg5t6rIFYFU1aF6LxQLtr4IcrwC1BJTJL3s8m/17smHRQU0SNsgwKglXYAqImr5IJ/J2d6hxPRS11FjuFb8IW/EYM0vMZ/9GPVCMuR1qw6DHcVkREFTzmDYsURtjebMRnhGnR52SI92ovxpbTd+y7uW7sm+36sYHDMvrjV15ui1yTnU=
script:
- docker build -t hellodocker HelloDocker/
- python testuselessfunctions.py
- ./test.sh
after_success:
- docker login quay.io -u="$QUAY_LOGIN" -p="$QUAY_PASSWORD"
- docker push hellodocker quay.io/ottojolanki/hellodocker
